import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
//import Image from "next/image";
import styles from "../styles/Home.module.css";
import AppLayout from "../components/AppLayout";

export default function Home() {
  const router = useRouter();

  console.log(router);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          <Link href="/timeline" target="_self">
            <a>go Timeline</a>
          </Link>
        </h1>
      </AppLayout>

      <footer className={styles.footer}></footer>
    </div>
  );
}
